import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import localFont from "next/font/local";

const poppins = Poppins({
  variable: "--poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "800", "900"],
});

const ButlerRegular = localFont({
  src: "../../public/fonts/ButlerRegular.woff",
  variable: "--ButlerRegular",
  display: "swap",
});

const ButlerUltraLight = localFont({
  src: "../../public/fonts/ButlerUltraLight.woff",
  variable: "--ButlerUltraLight",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${poppins.variable} ${ButlerRegular.variable} ${ButlerUltraLight.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
